spring:
  datasource:
    mysql:
      jcompany:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/jcompany?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: 1111
      jstore:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/jstore?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: 1111
      jcontract:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/jcontract?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: 1111
      jemployee:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/jemployee?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: 1111
    jta:
      jcompany:
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://127.0.0.1:3306/jcompany?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: 1111
      jstore:
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://127.0.0.1:3306/jstore?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: 1111
      jcontract:
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://127.0.0.1:3306/jcontract?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: 1111
      jemployee:
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://127.0.0.1:3306/jemployee?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: 1111
